meta_product_name: "GOM - The Great Outdoors Map"
meta_title: "GOM - The Great Outdoors Map"
meta_description: "Choose a region, a sport, and let's ride!"
meta_image: "banner.jpg" # should exist in `app/assets/images/`
twitter_account: "@Renodor"   # required for Twitter Cards
